#!/bin/sh
# A fast way of creating and editing notes using neovim without defining a file path

# Function to display help message
usage() {
    cat <<EOF
Usage: writedoc [options] FILENAME

  OPTIONS:
  -h          Display help information
  -c          Change the default values of directory and/or file type
              use with either -d, -t or -e to change the defaults
              FILENAME is not required and will be ignored
  -p          Use another folder in the default directory
              e.g. writedoc -p ExampleFolder ExampleFile =
              ~/Default/ExampleFolder/ExampleFile.md
  
  -r          Reset all values back to the default setting

  -d          Directory where the file will be created (default: ./Documents)

  -e          Change what editor to use (default: nvim)
  
  -t          File type of the file (default: .md)
  
  FILENAME    Name of the markdown file (without extension)
EOF
    exit 1
}

CHANGE=0
PFLAG=0

# Get directory and file type
DATA_DIR="/usr/share/writedoc"


config() {
    val=$(grep -E "^$1=" /home/$USER/.config/writedoc/writedoc.conf 2>/dev/null || echo "$1=__DEFAULT__" | head -n 1 | cut -d '=' -f 2-)

    if [[ $val == __DEFAULT__ ]]
    then
        case $1 in
            editor)
                echo -n "root"
                ;;
            password)
                echo -n ""
                ;;
            hostname)
                echo -n "localhost"
                ;;
        esac
    else
        echo -n $val
    fi
}

echo $(config username) # should be loaded from defaults
echo $(config password) # should be loaded from config file
echo $(config hostname) # includes the "injected" code, but it's fine here
echo $(config PROMPT_COMMAND) # also respects variables that you may not have
               # been looking for, but they're sandboxed inside the $config array



# Parse flags with getopts
while getopts ":cp:rd:t:e:h" OPTION; do
    case "$OPTION" in
        c) # Change defaults flag
            CHANGE=1
            ;;
        p) # + Folder
            PFLAG=1
            DIRECTORY="$DIRECTORY$OPTARG"
            ;;
        r) # Reset defaults
            echo "./Documents/" > "$dirInput" 
            echo ".md" > "ftInput"
            exit 0
            ;;
        d) # Directory
            DIRECTORY="$OPTARG"
            if [ $CHANGE -eq 1 ]; then
                echo "$DIRECTORY" > "$dirInput"
                exit 0
            fi
            ;;
        t) # File type
            FILETYPE="$OPTARG"
            if [ $CHANGE -eq 1 ]; then
                echo "$FILETYPE" > "$ftInput"
                exit 0
            fi
            ;;
        e) # Editor
            EDITOR="$OPTARG"
            if [ $CHANGE -eq 1 ]; then
                echo "$EDITOR" > "$edInput"
                exit 0
            fi
            ;;
        :)  # Handle missing arguments
            echo "Error: Option -$OPTARG requires an argument." >&2
            usage
            ;;
        h) # Help
            usage
            ;;
        \?) # Handle invalid options
            echo "Error: Invalid option -$OPTARG" >&2
            usage
            ;;
    esac
done

# Shift the processed options so that $1 is now the FILENAME
shift $((OPTIND - 1))

# Check if FILENAME is provided
if [ $# -eq 0 ]; then
    echo "Error: FILENAME is required." >&2
    usage
fi

FILENAME="$1"

# Make sure the directory exists - create if not
if [ ! -d "$DIRECTORY" ]; then
    echo "Directory does not exist. Creating it now..."
    mkdir -p "$DIRECTORY"
fi

# Make sure command (editor) exists
if command -v mycommand >/dev/null 2>&1; then
    echo "Editor $EDITOR does not exist!" >&2
    usage
fi


# Ensure DIRECTORY ends with a slash
DIRECTORY="${DIRECTORY%/}/"

# Construct the file path
FILEPATH="$DIRECTORY$FILENAME$FILETYPE"

# Create the markdown file with a simple title as content
if ! test -f $FILEPATH; then
    echo "Creating file at: $FILEPATH"
    if [ $FILETYPE -eq ".md" ]; then
        echo "# $FILENAME" > "$FILEPATH"
    fi
fi

# Open the file in Neovim
echo "Opening file with $EDITOR..."
$EDITOR "$FILEPATH"
