.\" Manpage for writedoc
.TH WRITEDOC 1 "May 2025" "writedoc 1.0" "User Commands"
.SH NAME
writedoc \- create markdown files quickly with customizable defaults
.SH SYNOPSIS
.B writedoc
[\-d DIR] [\-t FILETYPE] [\-c] [\-r] [\-p SUBDIR] [FILENAME]
.SH DESCRIPTION
.B writedoc
is a simple POSIX-compliant utility designed to simplify the creation of Markdown (or other) documents with user-defined or default locations and file types.

It allows users to specify the directory and file type of the file to be created, change or reset default values, or create files in subdirectories.

.SH OPTIONS
.TP
.B \-d DIR
Specify a custom directory for the new file.
.TP
.B \-t FILETYPE
Specify a custom file extension for the new file (e.g. \fB.md\fR, \fB.txt\fR, \fB.csv\fR).
.TP
.B \-c
Change the default values for directory and/or file type. Must be used with \fB\-d\fR and/or \fB\-t\fR. \fBFILENAME\fR is optional when using this flag.
.TP
.B \-r
Reset all values back to their defaults. \fBFILENAME\fR is not required.
.TP
.B \-p SUBDIR
Create the file in the default directory with an additional subdirectory.
.TP
.B FILENAME
Name of the file to create (without extension).

.SH DEFAULTS
Default directory: \fB./Documents/\fR  
Default file type: \fB.md\fR

.SH EXAMPLES
Create a file called \fBwork.md\fR in the default directory:
.PP
.B writedoc work
.PP
Create a file called \fBwork.csv\fR in \fB~/ImportantFiles/\fR:
.PP
.B writedoc \-d ~/ImportantFiles \-t .csv work
.PP
Change the default directory and file type:
.PP
.B writedoc \-c \-d ~/ImportantFiles \-t .csv
.PP
Reset the default values:
.PP
.B writedoc \-r
.PP
Create a file called \fBwork.md\fR in \fB./Documents/Important/\fR:
.PP
.B writedoc \-p Important work

.SH INSTALLATION
.SS Manual Install
Ensure you have \fBbase-devel\fR, \fBgit\fR, and \fBneovim\fR installed.

Clone the repository:
.PP
.B git clone https://github.com/Chiron8/writedoc
.BR
.B cd writedoc

.SS Build the package:
For Arch Linux and systems with \fBmakepkg\fR:
.PP
.B makepkg \-si

For other systems:
.PP
.B ./install.sh

.SH NOTES
The AUR version of \fBwritedoc\fR is outdated and has a broken PKGBUILD. Manual installation is strongly recommended.

.SH AUTHOR
Chiron

.SH BUGS
This is a work in progress. Expect updates, improvements, and breaking changes in future versions.

.SH SEE ALSO
.BR touch (1),
.BR mkdir (1),
.BR nvim (1)


